### ISSUE TITLE
structurefilelib.php issues.

### ISSUE THREAD

**Issue by danmarsden** [Laboratoire-de-Chemoinformatique/moodle-atto_molstructure#2]
* This file contains a mix of inline php and functions - functions must all sit somewhere like locallib.php or lib.php and you should not mix inline php code and functions within the same file.

* Functions must use our frankenstyle naming conventions as per: https://docs.moodle.org/dev/Frankenstyle - (the functions in this file do not use this.

* This file does not check if the user is logged in - it allows anonymous /non-logged in users to upload files.

* this file allows users to upload any file to any file area in Moodle - even areas they do not have access to, should not be able to upload files to - imagine a user being able to upload a course image to a course they do not have write access to - or many other issues this could cause.

* You should only be able to upload files into the atto_molstructures own file area, and appropriate capability / security checks should be implemented to ensure the user should be allowed to upload a file in the location being passed (can they access the course/area where this file is being uploaded etc.)

**Comment by danmarsden** [comment]
nice work - that looks a lot better than before!

The way you accept "any" contextid passed by the end user and then store the file within that context still feels a little wrong, partly as you don't validate access to the contextid (can this user actually access/store things within this contextid) and - I think (but could be wrong) that normally files stored within the user draft area use the users contextid - attaching the draft file to the user itself.

I've just checked in with the review team to see if anyone has time to give some further guidance on how you should be doing this.

**Comment by mudrd8mz** [comment]
Dan is right. It would be considered a security and data-loss risk bug if the plugin allowed to store files into unexpected areas. There are docs explaining the files handling at https://moodledev.io/docs/apis/subsystems/files#getting-files-from-the-user

**Comment by LouisPlyer** [comment]
Hello, I just updated the code to use the contextid of the user, can you take a look and tell me if I need to modify anything.

**Comment by danmarsden** [comment]
yeah that at least gets us over the compliance issue, if you re-package that up and submit the new version to the plugins db this might be ready to go after final checks. Thanks!

**Comment by LouisPlyer** [comment]
Perfect, I'm going to do that then !
