### ISSUE TITLE
Please create a version that works for TinyMCE?

### ISSUE THREAD

**Issue by Richardvi** [Laboratoire-de-Chemoinformatique/moodle-atto_molstructure#3]
Hi!

I just saw your plugin release: https://moodle.org/plugins/atto_molstructure

But... everyone is moving away from the Atto editor. Moodle goes full TinyMCE from version 4.2 and onwards. So I find it very sad that such a nice plugin has been build for a text editor that is being abandoned in Moodle.

Are you going to create a TinyMCE plugin as well, so that it will continue to work for Moodle 4.2 and higher versions?

**Comment by cperves** [comment]
Hello, I'm working on tiny implementation

**Comment by cperves** [comment]
New tiny version, full amd available
see https://moodle.org/plugins/tiny_molstructure

**Comment by Richardvi** [comment]
Thanks!!!!!
