### ISSUE TITLE
Button does not appear when I access the Atto HTML editor for a question in a quiz

### ISSUE THREAD

**Issue by caiadogithub** [Laboratoire-de-Chemoinformatique/moodle-atto_molstructure#5]
The plugin was installed correctly, as the button appears in the toolbar when I add a new discussion topic in the "News" Forum

However, the same button does not appear when I access the Atto HTML editor for a question in a quiz, for example.

![Firefox_Screenshot_2024-03-11T16-50-56 512Z](https://github.com/Laboratoire-de-Chemoinformatique/moodle-atto_molstructure/assets/23316275/9469174c-2b56-4a08-a3f6-b053e139b546)

![Firefox_Screenshot_2024-03-11T16-56-45 574Z](https://github.com/Laboratoire-de-Chemoinformatique/moodle-atto_molstructure/assets/23316275/2392f2d8-8389-4f4a-b5db-1c917e169aec)

**Comment by cperves** [comment]
reproduced:
* question type description
*  while student is responding
* despite of atto/molstructure:visible set to true for students

**Comment by cperves** [comment]
@caiadogithub , I solved the trouble
I push it on moodle.org
Thank you for this issue report

**Comment by caiadogithub** [comment]
Perfect!

**Comment by cperves** [comment]
new 4.1.2 version in moodle.org
